# Generated by Django 5.2.7 on 2025-11-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_personaldetail_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='class_name',
            field=models.CharField(blank=True, help_text='Applicable only for students', max_length=100, null=True),
        ),
    ]
