# Generated by Django 5.2.7 on 2025-11-07 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_personaldetail_class_name'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='class_name',
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Applicable only for students', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='timetable.classroom'),
        ),
    ]
